# What? 
- Numpy!
- https://numpy.org/
- https://numpy.org/devdocs/user/quickstart.html

## So What? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- Numpy is the most popular linear algebra library for Python
- Provides loop-like behavior w/o the overhead of loops or list comprehensions (vectorized operations)
- Provides list + loop + conditional behavior for filtering arrays

## Now What?
- Start working with numpy arrays! `np.array([1, 2, 3])` to create a numpy array!
- We'll start using built-in numpy functions all the time:
    - min, max, mean, sum, std
    - np.median, 
- Learn to use some vectorized operations
- Learn how to create arrays of booleans to filter results

In [1]:
import numpy as np

In [2]:
%%timeit
[x ** 2 for x in range(1, 1_000_000)]

370 ms ± 1.48 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit
np.arange(1, 1_000_000) ** 2

3.04 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
370 / 3.04

121.71052631578947

C is "closer to the metal" than Python

Assembly is closer to the metal than C

and Processor instruction sets == are the metal!

In [9]:
# Let's make our first numpy array!
x = [1, 2, 3, 4, 5]
x = np.array(x)
x, type(x)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [12]:
# shape tells us the shape of our n-dimensional array
x.shape

(5,)

In [13]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 0, 9]
])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [14]:
type(matrix)

numpy.ndarray

In [15]:
# List index syntax works on numpy arrays!
matrix[0]

array([1, 2, 3])

In [16]:
matrix[0][0]

1

In [17]:
matrix[0, 0]

1

In [18]:
first_row = matrix[0]
first_row

array([1, 2, 3])

In [19]:
first_element = first_row[0]
first_element

1

In [21]:
x, x[1:3]

(array([1, 2, 3, 4, 5]), array([2, 3]))

In [22]:
a = np.array(range(1, 100))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
a.sum(), a.mean(), a.min(), a.max(), a.std()

(4950, 50.0, 1, 99, 28.577380332470412)

In [25]:
# median is different (and there's some other functions that work similarly)
np.median(a)

50.0

In [28]:
b = np.array([2, 3, 4, 5])
should_include_elements = np.array([False, True, False, True])
b[should_include_elements]

array([3, 5])

In [31]:
should_include_elements = np.array([False, True, True])
matrix[should_include_elements]

array([[4, 5, 6],
       [7, 0, 9]])

## Arrays of Booleans == Beating Heart of Filtering/Transforming Arrays
- This is how we can do loop-like stuff w/o loops
- This "spell" is called "Boolean Masking" and folks may "array filtering" or "indexing"

In [32]:
x = np.array([1, 2, 3, 4, 5])

In [33]:
x == 3

array([False, False,  True, False, False])

In [34]:
x < -9

array([False, False, False, False, False])

In [35]:
x > 3

array([False, False, False,  True,  True])

In [36]:
x % 2 == 0

array([False,  True, False,  True, False])

In [37]:
only_threes = x == 3
x[only_threes]

array([3])

In [38]:
# We don't need the extra variable, however, we can do the following:
# I read this code almost like SQL in my head:
# Select X where X is equal to 3
x[x == 3]

array([3])

In [39]:
# Select X where X is less than zero
x[x < 0]

array([], dtype=int64)

In [40]:
# Select x where x is greater than 3
x[x > 3]

array([4, 5])

In [42]:
# Select x where x divided by two leaves no remainder
evens_from_x = x[x % 2 == 0]
evens_from_x

array([2, 4])

In [51]:
# In the Python admissions test, there was a question called "remove_evens" where you write a function that removes evens
# In base Python, this is a loop w/ a conditional and another operation to append to a list, or a list comprehension
def remove_evens(x):
    x = np.array(x)
    return x[x % 2 == 0]

y = remove_evens([2, 3, 34, 5, 6, 24, 442, 24, 12, 3, 24, 3, 3, 23, 23, 23, 10])
y

array([  2,  34,   6,  24, 442,  24,  12,  24,  10])

In [53]:
x = np.array([1, 2, "3", 4])

In [54]:
x

array(['1', '2', '3', '4'], dtype='<U21')

## Intro to Vectorization
- Loop like behavior on a array w/o the loop

In [56]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
x + 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
# Let's make an array of random integers
# start is inclusive, end is exclusive
# So the following line is like rolling a 20 sided die
x = np.random.randint(1, 21)
x

18

In [59]:
# 3rd argument is the size (or the number of random numbers)
x = np.random.randint(1, 21, 10)
x

array([ 1,  7,  6,  3,  1,  5,  6,  8, 13, 12])

In [61]:
# Let's make Python fall on its face
a = [1, 2, 3]

# In Python, how would we add one to every item on this list?
[n + 1 for n in a]

[2, 3, 4]

In [62]:
x + 1

array([ 2,  8,  7,  4,  2,  6,  7,  9, 14, 13])

In [63]:
# elementwise division
x / 10

array([0.1, 0.7, 0.6, 0.3, 0.1, 0.5, 0.6, 0.8, 1.3, 1.2])

In [67]:
# Vector addition
x + x

array([ 2, 14, 12,  6,  2, 10, 12, 16, 26, 24])

In [68]:
# scalar-vector multiplication along w/ vector subtraction
x - 2*x

array([ -1,  -7,  -6,  -3,  -1,  -5,  -6,  -8, -13, -12])

In [69]:
# There's many more linear algebra features
np.dot(x, x)

534

In [71]:
np.linalg.norm(x)

23.108440016582687

In [73]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
array_with_one_added

[2, 3, 4, 5, 6]

In [75]:
np.array(original_array) + 1

array([2, 3, 4, 5, 6])

In [76]:
beatles = np.array(["Ringo", "George", "Paul", "John"])

In [77]:
beatles == "Ringo"

array([ True, False, False, False])

In [79]:
beatles[beatles != "Ringo"]

array(['George', 'Paul', 'John'], dtype='<U6')

In [80]:
beatles[beatles == "Ringo"]

array(['Ringo'], dtype='<U6')

In [82]:
matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  0, 18]])

In [83]:
# Inner product
np.dot(x, x)

534

In [84]:
np.random.randn(10)

array([-1.62715121, -2.55822217,  0.55279875, -1.60457515, -0.99119666,
       -0.79798554,  1.29417286,  0.18299263,  0.72323591, -1.58823739])

In [86]:
np.random.randint(1, 7, 6)

array([2, 3, 1, 6, 3, 6])